name: Build and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build ./...

      - name: Update APT
        run: sudo apt-get update

      - name: Install test dependencies
        run: |
          sudo apt-get install -y \
            snapd \
            germinate \
            mtools \
            debootstrap \
            fdisk \
            gdisk \
            qemu-system-aarch64 \
            qemu-user-static \
            ubuntu-dev-tools

      - name: Run tests
        run: |
          go test -timeout 0 -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
